export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 79.99,
    rating: 4.5,
    stock: 12,
    image: "headphones",
    emoji: "🎧",
    color: "#4f46e5",
    description:
      "Over-ear wireless headphones with active noise cancellation and 30-hour battery life.",
  },
  {
    id: 2,
    name: "Smart Watch",
    category: "Electronics",
    price: 149.99,
    rating: 4.2,
    stock: 8,
    image: "smartwatch",
    emoji: "⌚",
    color: "#0891b2",
    description:
      "Track your fitness, heart rate, and notifications right from your wrist.",
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 39.99,
    rating: 4.0,
    stock: 20,
    image: "bluetooth,speaker",
    emoji: "🔊",
    color: "#7c3aed",
    description: "Portable speaker with rich bass and 12-hour playtime.",
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    rating: 4.7,
    stock: 15,
    image: "mechanical,keyboard",
    emoji: "⌨️",
    color: "#4338ca",
    description: "Tactile mechanical keyboard with RGB backlighting.",
  },
  {
    id: 5,
    name: "Men's Denim Jacket",
    category: "Fashion",
    price: 59.99,
    rating: 4.1,
    stock: 25,
    image: "denim,jacket",
    emoji: "🧥",
    color: "#1d4ed8",
    description: "Classic denim jacket, durable and stylish for everyday wear.",
  },
  {
    id: 6,
    name: "Running Shoes",
    category: "Fashion",
    price: 74.99,
    rating: 4.6,
    stock: 18,
    image: "running,shoes",
    emoji: "👟",
    color: "#dc2626",
    description: "Lightweight running shoes with breathable mesh upper.",
  },
  {
    id: 7,
    name: "Leather Wallet",
    category: "Fashion",
    price: 24.99,
    rating: 4.3,
    stock: 30,
    image: "leather,wallet",
    emoji: "👛",
    color: "#92400e",
    description: "Genuine leather bifold wallet with RFID protection.",
  },
  {
    id: 8,
    name: "Sunglasses",
    category: "Fashion",
    price: 34.99,
    rating: 4.0,
    stock: 22,
    image: "sunglasses",
    emoji: "🕶️",
    color: "#111827",
    description: "UV-protective polarized sunglasses with a classic frame.",
  },
  {
    id: 9,
    name: "Non-Stick Cookware Set",
    category: "Home & Kitchen",
    price: 129.99,
    rating: 4.4,
    stock: 10,
    image: "cookware,pots",
    emoji: "🍳",
    color: "#b45309",
    description: "10-piece non-stick cookware set, dishwasher safe.",
  },
  {
    id: 10,
    name: "Electric Kettle",
    category: "Home & Kitchen",
    price: 29.99,
    rating: 4.2,
    stock: 16,
    image: "electric,kettle",
    emoji: "🫖",
    color: "#0f766e",
    description: "Fast-boiling electric kettle with auto shut-off.",
  },
  {
    id: 11,
    name: "Memory Foam Pillow",
    category: "Home & Kitchen",
    price: 22.99,
    rating: 4.5,
    stock: 40,
    image: "pillow,bedding",
    emoji: "🛏️",
    color: "#6d28d9",
    description: "Ergonomic memory foam pillow for better neck support.",
  },
  {
    id: 12,
    name: "Scented Candle Set",
    category: "Home & Kitchen",
    price: 19.99,
    rating: 4.1,
    stock: 35,
    image: "scented,candle",
    emoji: "🕯️",
    color: "#be185d",
    description: "Set of 3 hand-poured soy candles in relaxing scents.",
  },
  {
    id: 13,
    name: "The Midnight Library",
    category: "Books",
    price: 14.99,
    rating: 4.8,
    stock: 50,
    image: "book,library",
    emoji: "📖",
    color: "#1e3a8a",
    description: "A bestselling novel about choices, regret, and hope.",
  },
  {
    id: 14,
    name: "Atomic Habits",
    category: "Books",
    price: 16.99,
    rating: 4.9,
    stock: 45,
    image: "book,stack",
    emoji: "📘",
    color: "#065f46",
    description: "A practical guide to building good habits and breaking bad ones.",
  },
  {
    id: 15,
    name: "Sketchbook (A4)",
    category: "Books",
    price: 9.99,
    rating: 4.3,
    stock: 60,
    image: "sketchbook,notebook",
    emoji: "📓",
    color: "#78350f",
    description: "Thick, acid-free paper sketchbook for artists.",
  },
  {
    id: 16,
    name: "Yoga Mat",
    category: "Sports",
    price: 27.99,
    rating: 4.5,
    stock: 28,
    image: "yoga,mat",
    emoji: "🧘",
    color: "#15803d",
    description: "Non-slip, extra-thick yoga mat with carry strap.",
  },
  {
    id: 17,
    name: "Adjustable Dumbbells",
    category: "Sports",
    price: 89.99,
    rating: 4.6,
    stock: 9,
    image: "dumbbells,weights",
    emoji: "🏋️",
    color: "#374151",
    description: "Space-saving adjustable dumbbells, 5-25 lbs per hand.",
  },
  {
    id: 18,
    name: "Basketball",
    category: "Sports",
    price: 24.99,
    rating: 4.4,
    stock: 33,
    image: "basketball",
    emoji: "🏀",
    color: "#c2410c",
    description: "Official size and weight basketball for indoor/outdoor use.",
  },
];
